from Animal import *
from Shape import *
print("---Dog----")
D = Dog("Biscuit","Brown",2,4,1)    
print(D.get_eat())
print(D.get_color())
print(D.get_eyes())
print(D.get_legs())
print(D.get_tail())
print(D.gettype())

print()
print("---Cat---")
C = Cat("Roti/Milk","Black",2,4,1)    
print(C.get_eat())
print(C.get_color())
print(C.get_eyes())
print(C.get_legs())
print(C.get_tail())
print(C.gettype())

print()
print("---Deer---")
H = Deer("Anything","Brown",2,4,1,2)
print(H.get_eat())
print(H.get_color())
print(H.get_eyes())
print(H.get_legs())
print(H.get_tail())
print(H.get_horn())
print(H.gettype())

print()
print("---Rabbit---")
R = Rabbit("Anything","Brown",2,4,1,"Wool")
print(R.get_eat())
print(R.get_color())
print(R.get_eyes())
print(R.get_legs())
print(R.get_tail())
print(R.get_use())
print(R.gettype())
print("---Cow---")

print()
O = Cow("Anything","Brown",2,4,1,"Milk")
print(O.get_eat())
print(O.get_color())
print(O.get_eyes())
print(O.get_legs())
print(O.get_tail())
print(O.get_give())
print(O.gettype())

print()
print("---Elephant---")
E = Elephant("Anything","Brown",2,4,1,1)
print(E.get_eat())
print(E.get_color())
print(E.get_eyes())
print(E.get_legs())
print(E.get_tail())
print(E.get_trunk())
print(E.gettype())

print()
print("---Horse---")
S = Horse("Anything","Brown",2,4,1,"Transport")
print(S.get_eat())
print(S.get_color())
print(S.get_eyes())
print(S.get_legs())
print(S.get_tail())
print(S.get_use())
print(S.gettype())

print()
F = Fish("Algae","Multicolor",2,"Cold Blooded","Yes","Cat Fish","Anal Fins")
print(F.get_eyes())
print(F.get_eat())
print(F.get_color())
print(F.get_swim())
print(F.get_blooded())
print(F.get_type())
print(F.get_fintype())
print(F.gettype())

print()
print("----Octopus-----")
Oc = Octopus("Crustaceans,worms","Pink",2,"Cold Blooded","yes",8)
print("Eat = ",Oc.get_eat())
print("Color = ",Oc.get_color())
print("Eyes = ",Oc.get_eyes())
print("Blooded = ",Oc.get_blooded())
print("Swim = ",Oc.get_swim())
print("Arms = ",Oc.get_arms())

print()
print("-----Dolphin-----")
do = Dolphin("Animal","Blue",2,"Cold Blooded","yes","Dorsal fin",104)
print("Eat = ",do.get_eat())
print("Color = ",do.get_color())
print("Eyes = ",do.get_eyes())
print("Blooded = ",do.get_blooded())
print("Swim = ",do.get_swim())
print("Teeth = ",do.get_teeth())
print("Fintype = ",do.get_fintype())
print("Teeth = ",do.get_teeth())


